environment:
  MONGODB_URI: "${MONGODB_URI}"
packages:
  - name: user
    functions:
      - name: getDashboard
        binary: false
        runtime: nodejs:18
        web: true
        webSecure: false
